spring.application.name=FullstackTM

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=rootGrays
spring.jpa.hibernate.ddl-auto=update